[tool.poetry]
name = "jobapplicationtracker"
version = "0.1.0"
description = ""
authors = ["Tamagil <tamagiltamagil@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.2.3"
djangorestframework = "^3.16.0"
dotenv = "^0.9.9"
psycopg2 = "^2.9.10"
psycopg2-binary = "^2.9.10"
django-money = "^3.5.4"
django-cities-light = "^3.10.1"
django-autocomplete-light = "^3.12.1"
pre-commit = "^4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
